kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: capa-lfs256
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
# the three workers
- role: worker
  extraPortMappings:
  - containerPort: 31120
    hostPort: 31120
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp