resources:
- https://raw.githubusercontent.com/lftraining/LFS256-code/main/argoevents/pulsar.yaml
- https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/event-sources/pulsar.yaml
- https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/sensors/pulsar.yaml

patches:
 - target:
      group: ""
      version: v1
      kind: Service
      name: pulsar
   path: svc-patch.yaml
 - target:
      group: argoproj.io
      version: v1alpha1
      kind: Sensor
      name: pulsar
   path: pulsar-image.yaml
