apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argowf

# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: argowf

resources:
# - https://github.com/argoproj/argo-workflows/manifests/cluster-install/?timeout=120&ref=v3.5.2
- https://github.com/argoproj/argo-events/manifests/cluster-install/?timeout=120&ref=v1.9.7
# - https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install.yaml
- https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install-validating-webhook.yaml
# - vs.yaml
# - gw.yaml
